### ISSUE TITLE
After HomeAssistant update, using HA to turn on/off switches not working

### ISSUE THREAD

**Issue by LukeMondy** [mattsaxon/sonoff-lan-mode-homeassistant#37] opened 2020-05-02 13:03 UTC
Hello,

I did an update of my home assistant today, to 0.109.2, and now it seems my ability to control switches from HA has stopped working. If I switch them by hand, HA does notice, and update their status.

When I look at the logs of the docker container, I see this when I try to switch a switch:
```
2020-05-02 23:00:39 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _available: True
/usr/local/lib/python3.7/asyncio/base_events.py:1787: RuntimeWarning: coroutine 'HassSonoffSwitchR3.turn_off' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback```
```

Any ideas?

I've just updated my HA to have the latest master of this repo too.

**Comment by mattsaxon** [comment] 2020-05-02 13:54
Have you got 1.1.4.1 version which I just updated this morning?

**Comment by mattsaxon** [comment] 2020-05-02 14:11
Duplicate of https://github.com/mattsaxon/sonoff-lan-mode-homeassistant/issues/34

**Comment by LukeMondy** [comment] 2020-05-02 23:23
I thought I had, but I made a mistake 😓 
Updating it correctly fixed it - thanks, and sorry for the spurious report!

**Closed as completed** 2020-05-02 23:25 UTC
