### ISSUE TITLE
Add sensor information for ifan02

### ISSUE THREAD

**Issue by tsouza85** [mattsaxon/sonoff-lan-mode-homeassistant#12] opened 2019-12-15 19:52 UTC
Config:
```
  - platform: sonoff_lan_mode_r3
    name: ifan02
    device_id: 100065d0d6
    api_key: 444daa51-d78c-4802-8463-663bd2788f70
```
Log:

> 2019-12-15 16:50:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff_lan_mode_r3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2019-12-15 16:50:02 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Initializing SonoffLANModeClient class in SonoffDevice
> 2019-12-15 16:50:02 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch __init__ finished creating SonoffSwitch
> 2019-12-15 16:50:02 INFO (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] Service type _ewelink._tcp.local. of name eWeLink_100065d0d6._ewelink._tcp.local. added
> 2019-12-15 16:50:02 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] service is at 192.168.0.113:8081
> 2019-12-15 16:50:02 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] properties: {b'txtvers': b'1', b'id': b'100065d0d6', b'type': b'strip', b'apivers': b'1', b'seq': b'11', b'encrypt': True, b'iv': b'MDk5MjQ0MDE4MzAxNTYzOA==', b'data1': b'IQDCz2/RtJmOuFqYNCeDOjaaBHAdi1rCE3XgqZiYutmEdFpaWnW2tMR76bLBGaZ3tU78ZxsjStzNACaeq0TmE1ktruCgUCw8gwmmMxmYH8fz9ejAWsfBBAABWqrTQ+ZsJeyClTfZ2wIT4s/nIQgQtbQELX1ITtrzIM0Bmf9iAmJc0cpJdbk5WQSpMMXn1tEDhPbnF4t0eHSoXzxGb16WKmwDyFjucnwxyOdsoHBjXAGTI5c7ViaQq4v2s', b'data2': b'hApm9dAAzwQKY3R4jm+dze2kNqhGvICuvJzZNcTJC0kWbRnnIcw+nO/G2aHVu9R1jLabdOnu+TCrMdCINSY2FQCLtgQBFgCxHEX2szX9s2NO/BxKGsVB3sFHOrgBIy/Pno+ugmM+MFVlxO5EhNzP64OQhinIou/QEfadnFVbpdZ11NPI9Rp1a3Qpoo9OA0w5d454e9Hd6eYHJMJw8D3UWCRjtT5pWmqq47OHg3nWHpqfk6U/CxM1K+npg', b'data3': b'esLdeinCs1Nr4rcnJALLk1hADxcVZvSgvk6bSh6FAUapslpCoUQ58lNuAV09JAnHboifwNj6q75RsQzkMTVgNokq8UUZ7eaZHN0g=='}
> 2019-12-15 16:50:02 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] type: b'strip'
> 2019-12-15 16:50:02 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] decrypted data: b'{"sledOnline":"on","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"switches":[{"switch":"off","outlet":0},{"switch":"on","outlet":1},{"switch":"off","outlet":2},{"switch":"on","outlet":3}]}'
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] enter send_availability_loop()
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] waiting for connection
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] send_updated_params_loop is active on the event loop
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Starting loop waiting for device params to change
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] send_updated_params_loop now awaiting event
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch async_update called
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Sonoff device basic info still none, waiting for init message
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: ifan02
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _available: False
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: ifan02
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] enter handle_mesage()
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Message: Received status from device, storing in instance
> 2019-12-15 16:50:03 INFO (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] unsolicited update received from switch: off
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Switch update pre-callback filter running
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Not inching switch, calling parent callback
> 2019-12-15 16:50:03 INFO (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Sonoff LAN Mode switch ifan02 received updated state from the device: OFF, available: True
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch async_update called
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] connected event, sending update
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Switch update pre-callback filter running
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Not inching switch, calling parent callback
> 2019-12-15 16:50:03 INFO (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Sonoff LAN Mode switch ifan02 received updated state from the device: OFF, available: True
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch async_update called
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] waiting for disconnection
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _available: True
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _state: False
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: ifan02
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: ifan02
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _available: True
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _state: False
> 2019-12-15 16:50:03 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: ifan02

**Comment by mattsaxon** [comment] 2019-12-15 20:34
This issue is related to another one where I haven’t enabled multi outlets yet. I hope to get round to fixing this over the Xmas break

**Comment by mattsaxon** [comment] 2019-12-23 14:01
closing as duplicate of #4

**Comment by mattsaxon** [comment] 2019-12-23 14:13
Thanks for posting the debug information. Unfortunately it does not seem to have any sensor data in it.....

> b'{"sledOnline":"on","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"switches":[{"switch":"off","outlet":0},{"switch":"on","outlet":1},{"switch":"off","outlet":2},{"switch":"on","outlet":3}]}'

This just looks like a normal (4 way) switch. I don't know what the iFan02 should have as sensor data, can you elaborate what you think it should have?

**Comment by tsouza85** [comment] 2019-12-27 05:33
Only 3 switches:

- Fan
- Light
- Speed fan max

_There are no sensors!_

**Comment by mattsaxon** [comment] 2019-12-27 09:24
Ah, ok, so this should work now. You need to add all 3 switches as seperate findings and add the ‘outlet:’ parameter. any issue with this, please reply on the multi - outlet issues. I’ll close this one now.

**Closed as completed by mattsaxon** 2019-12-27 09:24 UTC
Labels: enhancement, help wanted
